[build]
  base = "frontend/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.12"

# Redirect API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For all other routes, serve the React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
