services:
  # Backend API service
  - type: web
    name: steadygains-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://steadygains-dashboard.onrender.com

  # Frontend static site
  - type: web
    name: steadygains-dashboard
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        value: https://steadygains-api.onrender.com
